#!/bin/bash
# =====================================================================
# Administration Système, Administration Réseau, etc ...
# Programme concédé sous licence GPL-V3, une création de Jason GOUZIEN.
# =====================================================================
# Date de création      : 30-09-2020.
# Date de modification  : 01-10-2020.
# =====================================================================

# deb : couleur de police.
cr_noir="\E[1;30m"
cr_vert="\E[1;32m"
cr_bleu="\E[1;34m"
cr_cyan="\E[1;36m"
cr_jaune="\E[1;33m"
cr_blanc="\E[1;37m"
cr_rouge="\E[1;31m"
cr_normal="\E[1;0m"
# fin : couleur de police.

# deb : couleur de fond.
fd_noir="\E[1;40m"
fd_vert="\E[1;42m"
fd_bleu="\E[1;44m"
fd_cyan="\E[1;46m"
fd_jaune="\E[1;43m"
fd_blanc="\E[1;47m"
fd_rouge="\E[1;41m"
# fin : couleur de fond.

# deb : fonctions édition.
sp_noir="${cr_noir}-${cr_normal}"
rr_ligne="\n"
ligne_noir="${cr_noir}========================================================${cr_normal}"
separation_noir="${cr_noir}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${cr_normal}"
# fin : fonctions édition.

# deb : répértoires.
OS="core/OS/"
RESEAU="core/RESEAU/"
UTILITAIRES="core/UTILITAIRES/"
# fin : répértoires.

# deb : script infos.
script_nom="${cr_cyan}BC SYSADMIN${cr_normal}"
script_auteur="${cr_jaune}Par : Jason GOUZIEN${cr_normal}"
script_version="${cr_vert}Version : 1.0.0.${cr_normal}"
# fin : script infos.

# deb : banniere "principal" script.
banniere_principal()
{
    printf "${ligne_noir}"${rr_ligne}
    printf "${cr_noir}[${cr_normal} $script_nom $sp_noir $script_auteur $sp_noir $script_version ${cr_noir}]${cr_normal}"${rr_ligne}
    printf "${ligne_noir}"${rr_ligne}
}
# fin : banniere "principal" script.