#!data/data/com.termux/files/usr/bin/bash
# =====================================================================
# Administration Système, Administration Réseau, etc ...
# Programme concédé sous licence GPL-V3, une création de Jason GOUZIEN.
# =====================================================================
# Date de création      : 12-10-2020.
# Date de modification  : 12-10-2020.
# =====================================================================

. core/configr_files/configuration # importe les fonctions principales.

menu_select_utilitaires()
{
    printf "${cr_rouge}[ 01 ]${cr_normal} Option(s) : Afficher Infos Système."${rr_ligne}

    printf "${ligne_noir}"${rr_ligne}

    read -p "[ == ] Choisissez une option : " votre_selection

    case $votre_selection in 
        "1"|"01") clear
        banniere_principal
        ./${UTILITAIRES}neofetch/neofetch
            ;;
    esac
}

clear
banniere_principal
menu_select_utilitaires